import { FormEvent, useEffect, useState } from "react";
import { Edit3, Save, Trash2, X } from "lucide-react";
import type { SupabaseSession } from "@/lib/supabase-auth";
import { createExtra, deleteExtra, emptyDocument, emptyMap, emptyMedia, emptyStaff, listDocuments, listMapItems, listMedia, listStaff, updateExtra } from "@/lib/extra-content-api";

type Mode="staff"|"documents"|"media"|"map";
const defs={staff:{label:"Ходимлар",table:"staff",empty:emptyStaff,load:listStaff},documents:{label:"Ҳужжатлар",table:"documents",empty:emptyDocument,load:listDocuments},media:{label:"Медиа",table:"media_items",empty:emptyMedia,load:listMedia},map:{label:"Харита объектлари",table:"map_objects",empty:emptyMap,load:listMapItems}} as const;
const langs=[["uz","Ўзбекча"],["ru","Русский"],["en","English"],["zh","中文"]] as const;
const input="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100";
export function ExtraManagers({session}:{session:SupabaseSession}){
 const [mode,setMode]=useState<Mode>("staff"),[items,setItems]=useState<any[]>([]),[form,setForm]=useState<any>(emptyStaff()),[editing,setEditing]=useState<string|null>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false);
 const def=defs[mode];
 async function reload(){try{setItems(await def.load(false,session) as any[])}catch(e){setMsg(e instanceof Error?e.message:"Юклашда хато")}}
 useEffect(()=>{setForm(def.empty());setEditing(null);void reload()},[mode]);
 function reset(){setForm(def.empty());setEditing(null)}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg("");try{editing?await updateExtra(def.table,editing,form,session):await createExtra(def.table,form,session);reset();await reload();setMsg("Маълумот сақланди.")}catch(x){setMsg(x instanceof Error?x.message:"Сақлашда хато")}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm("Ўчиришни тасдиқлайсизми?"))return;await deleteExtra(def.table,id,session);await reload()}
 const set=(k:string,v:any)=>setForm((c:any)=>({...c,[k]:v}));
 return <section id="extra-content" className="mt-8 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-2xl font-extrabold">Қўшимча бўлимларни бошқариш</h2><p className="mt-1 text-sm text-slate-500">Ходимлар, ҳужжатлар, медиа ва харита объектлари.</p></div><div className="flex flex-wrap rounded-xl bg-slate-100 p-1">{(Object.keys(defs) as Mode[]).map(k=><button key={k} onClick={()=>setMode(k)} className={`rounded-lg px-3 py-2 text-sm font-bold ${mode===k?"bg-white text-blue-700 shadow":"text-slate-600"}`}>{defs[k].label}</button>)}</div></div>{msg&&<p className="mt-5 rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-800">{msg}</p>}
 <form onSubmit={submit} className="mt-6 rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="flex justify-between"><h3 className="font-extrabold">{editing?"Таҳрирлаш":"Янги маълумот"}</h3>{editing&&<button type="button" onClick={reset} className="flex gap-2 text-sm font-bold"><X className="size-4"/>Бекор қилиш</button>}</div>
 {(mode==="staff"||mode==="media"||mode==="map")&&<div className="mt-5 grid gap-4 lg:grid-cols-2">{langs.map(([c,l])=><div key={c} className="rounded-xl bg-white p-4"><b className="text-blue-800">{l}</b><label className="mt-3 block text-sm font-bold">{mode==="staff"?"Ф.И.Ш.":"Сарлавҳа"}<input className={input} value={form[`${mode==="staff"?"name":"title"}_${c}`]||""} onChange={e=>set(`${mode==="staff"?"name":"title"}_${c}`,e.target.value)}/></label>{mode!=="staff"&&<label className="mt-3 block text-sm font-bold">Тавсиф<textarea className={input} rows={3} value={form[`description_${c}`]||""} onChange={e=>set(`description_${c}`,e.target.value)}/></label>}{mode==="staff"&&<label className="mt-3 block text-sm font-bold">Лавозим<input className={input} value={form[`role_${c}`]||""} onChange={e=>set(`role_${c}`,e.target.value)}/></label>}</div>)}</div>}
 {mode==="documents"&&<div className="mt-5 grid gap-4 lg:grid-cols-2">{langs.map(([c,l])=><label key={c} className="block rounded-xl bg-white p-4 text-sm font-bold">{l} — номи<input className={input} value={form[`title_${c}`]||""} onChange={e=>set(`title_${c}`,e.target.value)}/></label>)}</div>}
 <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
 {mode==="staff"&&<><label className="text-sm font-bold">Телефон<input className={input} value={form.phone||""} onChange={e=>set("phone",e.target.value)}/></label><label className="text-sm font-bold">Email<input className={input} value={form.email||""} onChange={e=>set("email",e.target.value)}/></label><label className="text-sm font-bold">Расм URL<input className={input} value={form.image_url||""} onChange={e=>set("image_url",e.target.value)}/></label><label className="text-sm font-bold">Тартиб<input type="number" className={input} value={form.sort_order||0} onChange={e=>set("sort_order",Number(e.target.value))}/></label></>}
 {mode==="documents"&&<><label className="text-sm font-bold">Файл тури<input className={input} value={form.file_type||""} onChange={e=>set("file_type",e.target.value)}/></label><label className="text-sm font-bold">Сана<input type="date" className={input} value={form.document_date||""} onChange={e=>set("document_date",e.target.value)}/></label><label className="text-sm font-bold md:col-span-2">Файл URL<input className={input} value={form.file_url||""} onChange={e=>set("file_url",e.target.value)}/></label></>}
 {mode==="media"&&<><label className="text-sm font-bold">Тури<select className={input} value={form.media_type} onChange={e=>set("media_type",e.target.value)}><option value="image">Расм</option><option value="video">Видео</option></select></label><label className="text-sm font-bold">Медиа URL<input className={input} value={form.media_url||""} onChange={e=>set("media_url",e.target.value)}/></label><label className="text-sm font-bold md:col-span-2">Превью URL<input className={input} value={form.thumbnail_url||""} onChange={e=>set("thumbnail_url",e.target.value)}/></label></>}
 {mode==="map"&&<><label className="text-sm font-bold">Кенглик<input type="number" step="any" className={input} value={form.latitude} onChange={e=>set("latitude",Number(e.target.value))}/></label><label className="text-sm font-bold">Узунлик<input type="number" step="any" className={input} value={form.longitude} onChange={e=>set("longitude",Number(e.target.value))}/></label><label className="text-sm font-bold">Категория<input className={input} value={form.category||""} onChange={e=>set("category",e.target.value)}/></label><label className="text-sm font-bold">Манзил<input className={input} value={form.address||""} onChange={e=>set("address",e.target.value)}/></label></>}
 <label className="flex items-center gap-3 rounded-xl border bg-white px-4 py-3"><input type="checkbox" checked={!!form.is_published} onChange={e=>set("is_published",e.target.checked)}/><b className="text-sm">Сайтда кўрсатиш</b></label></div>
 <button disabled={busy} className="mt-5 flex items-center gap-2 rounded-xl bg-blue-700 px-6 py-3 text-sm font-bold text-white"><Save className="size-4"/>{busy?"Сақланмоқда...":"Сақлаш"}</button></form>
 <div className="mt-6 space-y-3">{items.map((x:any)=><article key={x.id} className="flex items-center gap-3 rounded-xl border p-4"><div className="min-w-0 flex-1"><b>{x.name_uz||x.title_uz||x.address||"Маълумот"}</b><p className="mt-1 truncate text-sm text-slate-500">{x.role_uz||x.file_url||x.media_url||x.category}</p></div><button onClick={()=>{setEditing(x.id);setForm({...x})}} className="p-2 text-blue-700"><Edit3/></button><button onClick={()=>void remove(x.id)} className="p-2 text-red-600"><Trash2/></button></article>)}</div></section>
}
