import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Building2, CalendarDays, CheckCircle2, Download, Factory, FileText, Globe2, Landmark, Mail, MapPin, Phone, Search, Send, Users, BriefcaseBusiness, Image as ImageIcon, ShieldCheck, ExternalLink } from "lucide-react";
import { PageHero, SiteLayout } from "@/components/layout/SiteLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { projects, districts, exportPartners, local } from "@/components/site/data";
import { L, pageSubtitle, uiText } from "@/components/site/localized-content";
import { CONTACTS } from "@/lib/site-config";
import { useI18n } from "@/i18n";

const staff = [
  {name:L("Бошқарма бошлиғи","Начальник управления","Head of department","管理局局长"),role:L("Раҳбарият","Руководство","Management","管理层"),email:"info@surxondaryo-invest.uz"},
  {name:L("Инвестициялар бўлими бошлиғи","Начальник отдела инвестиций","Head of investment division","投资处负责人"),role:L("Инвестициялар","Инвестиции","Investment","投资"),email:"investment@surxondaryo-invest.uz"},
  {name:L("Саноатни ривожлантириш бўлими","Отдел развития промышленности","Industry development division","工业发展处"),role:L("Саноат","Промышленность","Industry","工业"),email:"industry@surxondaryo-invest.uz"},
  {name:L("Экспортни қўллаб-қувватлаш бўлими","Отдел поддержки экспорта","Export support division","出口支持处"),role:L("Ташқи савдо","Внешняя торговля","Foreign trade","外贸"),email:"export@surxondaryo-invest.uz"},
];
const news = [
 {title:L("2026 йил инвестиция дастури ижроси","Исполнение инвестиционной программы 2026 года","Implementation of the 2026 investment programme","2026年投资计划实施情况"),date:"31.07.2026",text:L("Ҳудудий лойиҳалар, ўзлаштирилган инвестициялар ва янги иш ўринлари бўйича натижалар.","Результаты по региональным проектам, освоенным инвестициям и новым рабочим местам.","Results on regional projects, utilized investment and new jobs.","区域项目、投资利用和新增就业成果。")},
 {title:L("Экспортчилар билан очиқ мулоқот","Открытый диалог с экспортёрами","Open dialogue with exporters","与出口商公开对话"),date:"25.07.2026",text:L("Сертификатлаш, логистика ва янги бозорларга чиқиш масалалари муҳокама қилинди.","Обсуждены сертификация, логистика и выход на новые рынки.","Certification, logistics and access to new markets were discussed.","讨论认证、物流和开拓新市场。")},
 {title:L("Хорижий инвесторлар учун янги таклифлар","Новые предложения для иностранных инвесторов","New offers for foreign investors","面向外国投资者的新提案"),date:"18.07.2026",text:L("Саноат, агросаноат, туризм ва логистика йўналишларида таклифлар тақдим этилди.","Представлены предложения в промышленности, агробизнесе, туризме и логистике.","Offers were presented in industry, agribusiness, tourism and logistics.","发布工业、农业、旅游和物流领域提案。")},
];
const docs = [
 {title:L("2026 йил 1-ярим йилликда амалга оширилган ишлар","Работы, выполненные в первом полугодии 2026 года","Work completed in the first half of 2026","2026年上半年完成的工作"),type:"DOCX",date:"2026",href:"/documents/2026-1-yarim-yillik.docx"},
 {title:L("Инвестиция лойиҳаси паспорти намунаси","Образец паспорта инвестиционного проекта","Investment project passport template","投资项目护照模板"),type:"PDF",date:"2026",href:"#"},
 {title:L("Экспортчилар учун мурожаат шакли","Форма обращения для экспортёров","Exporter application form","出口商申请表"),type:"DOCX",date:"2026",href:"#"},
];
const structures = [
 L("Раҳбарият","Руководство","Management","管理层"),L("Инвестицияларни жалб қилиш бўлими","Отдел привлечения инвестиций","Investment attraction division","招商处"),L("Саноатни ривожлантириш бўлими","Отдел развития промышленности","Industry development division","工业发展处"),L("Экспортни қўллаб-қувватлаш бўлими","Отдел поддержки экспорта","Export support division","出口支持处"),L("Хорижий ҳамкорлик бўлими","Отдел международного сотрудничества","International cooperation division","国际合作处"),L("Мурожаатлар билан ишлаш бўлими","Отдел по работе с обращениями","Appeals division","信访处")
];
const cardSets = {
 investments:[
  [BriefcaseBusiness,L("Инвестиция таклифлари","Инвестиционные предложения","Investment proposals","投资提案"),L("Саноат, агросаноат, логистика, туризм ва хизматлар соҳалари бўйича тайёр лойиҳалар.","Готовые проекты в промышленности, агробизнесе, логистике, туризме и услугах.","Ready projects in industry, agribusiness, logistics, tourism and services.","工业、农业、物流、旅游和服务业的成熟项目。")],
  [Users,L("Инвесторларга ҳамроҳлик","Сопровождение инвесторов","Investor support","投资者支持"),L("Лойиҳа ғоясидан ишга туширишгача бир дарча тамойилида амалий кўмак.","Практическая поддержка по принципу одного окна от идеи до запуска.","One-stop practical support from idea to launch.","从构想到投产的一站式支持。")],
  [ShieldCheck,L("Имтиёз ва преференциялар","Льготы и преференции","Benefits and preferences","优惠政策"),L("Солиқ, божхона ва инфратузилма имкониятлари.","Налоговые, таможенные и инфраструктурные возможности.","Tax, customs and infrastructure opportunities.","税收、海关和基础设施优惠。")],
 ],
 industry:[
  [Factory,L("Енгил саноат","Лёгкая промышленность","Light industry","轻工业"),L("Тўқимачилик, тайёр кийим ва чарм-пойабзал ишлаб чиқариш.","Текстиль, одежда и кожевенно-обувное производство.","Textiles, garments, leather and footwear.","纺织、服装、皮革和鞋类。")],
  [Building2,L("Қурилиш материаллари","Строительные материалы","Building materials","建材"),L("Цемент, гипс, базальт, мармар ва маҳаллий хомашёларни қайта ишлаш.","Переработка цемента, гипса, базальта, мрамора и местного сырья.","Processing cement, gypsum, basalt, marble and local raw materials.","水泥、石膏、玄武岩、大理石等加工。")],
  [Landmark,L("Озиқ-овқат саноати","Пищевая промышленность","Food industry","食品工业"),L("Мева-сабзавотни сақлаш, қайта ишлаш, қадоқлаш ва экспорт қилиш.","Хранение, переработка, упаковка и экспорт плодоовощной продукции.","Storage, processing, packaging and export of fruit and vegetables.","果蔬储存、加工、包装和出口。")],
 ],
 services:[
  [MapPin,L("Ер ва инфратузилма","Земля и инфраструктура","Land and infrastructure","土地与基础设施"),L("Ер, электр, газ, сув ва йўл инфратузилмаси бўйича маълумот.","Информация о земле, электричестве, газе, воде и дорогах.","Information about land, power, gas, water and roads.","土地、电力、燃气、供水和道路信息。")],
  [Globe2,L("Экспортга кўмак","Поддержка экспорта","Export support","出口支持"),L("Сертификатлаш, божхона, логистика ва ташқи бозорларга чиқиш.","Сертификация, таможня, логистика и выход на внешние рынки.","Certification, customs, logistics and market access.","认证、海关、物流和市场准入。")],
  [FileText,L("Лойиҳа ҳужжатлари","Проектная документация","Project documents","项目文件"),L("Бизнес-режа, техник-иқтисодий асос ва инвестиция паспорти.","Бизнес-план, ТЭО и инвестиционный паспорт.","Business plan, feasibility study and investment passport.","商业计划、可研和投资护照。")],
 ]
};

function SearchBox({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <div className="relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="pl-10"/></div>}

export function PortalPage({page,title}:{page:string;title:string}){
 const {lang,t}=useI18n(); const [query,setQuery]=useState(""); const [sent,setSent]=useState(false); const tx=(v:any)=>local(v,lang);
 const filteredProjects=useMemo(()=>projects.filter(p=>`${tx(p.title)} ${tx(p.sector)} ${tx(p.district)}`.toLowerCase().includes(query.toLowerCase())),[query,lang]);
 const filteredStaff=useMemo(()=>staff.filter(s=>`${tx(s.name)} ${tx(s.role)}`.toLowerCase().includes(query.toLowerCase())),[query,lang]);
 const filteredDocs=useMemo(()=>docs.filter(d=>tx(d.title).toLowerCase().includes(query.toLowerCase())),[query,lang]);
 let content:any;
 if(page==="projects") content=<><SearchBox value={query} onChange={setQuery} placeholder={tx(uiText.searchProject)}/><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filteredProjects.map(p=><article key={tx(p.title)} className="rounded-2xl border border-border bg-card p-6"><span className="text-xs font-semibold uppercase tracking-wide text-green">{tx(p.sector)}</span><h3 className="mt-3 text-lg font-bold">{tx(p.title)}</h3><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="text-muted-foreground">{tx(uiText.value)}</p><b>{p.amount}</b></div><div><p className="text-muted-foreground">{tx(uiText.jobs)}</p><b>{p.jobs}</b></div><div><p className="text-muted-foreground">{tx(uiText.area)}</p><b>{tx(p.district)}</b></div><div><p className="text-muted-foreground">{tx(uiText.status)}</p><b>{tx(p.status)}</b></div></div><Button className="mt-6 w-full">{t("common.more")} <ArrowRight className="size-4"/></Button></article>)}</div></>;
 else if(page==="staff"||page==="leadership") content=<><SearchBox value={query} onChange={setQuery} placeholder={tx(uiText.searchStaff)}/><div className="mt-8 grid gap-5 md:grid-cols-2">{filteredStaff.map((s,i)=><article key={tx(s.name)} className="flex gap-5 rounded-2xl border border-border bg-card p-6"><div className="flex size-16 shrink-0 items-center justify-center rounded-full gradient-brand text-xl font-bold text-white">{i+1}</div><div><p className="text-xs font-semibold uppercase tracking-wide text-green">{tx(s.role)}</p><h3 className="mt-1 text-lg font-bold">{tx(s.name)}</h3><a className="mt-3 flex items-center gap-2 text-sm text-muted-foreground" href="tel:+998762241415"><Phone className="size-4"/>{CONTACTS.phones[0]}</a><a className="mt-2 flex items-center gap-2 text-sm text-muted-foreground" href={`mailto:${s.email}`}><Mail className="size-4"/>{s.email}</a></div></article>)}</div></>;
 else if(page==="structure") content=<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{structures.map((x,i)=><article key={tx(x)} className="rounded-2xl border border-border bg-card p-6"><span className="text-3xl font-black text-primary/20">0{i+1}</span><h3 className="mt-3 font-bold">{tx(x)}</h3><p className="mt-2 text-sm text-muted-foreground">{tx(L("Бўлим вазифалари, масъул ходимлар ва алоқа маълумотлари.","Задачи отдела, ответственные сотрудники и контакты.","Department duties, responsible staff and contacts.","部门职责、负责人及联系方式。"))}</p></article>)}</div>;
 else if(page==="land") content=<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{districts.map(d=><article key={d.id} className="rounded-2xl border border-border bg-card p-6"><MapPin className="size-6 text-green"/><h3 className="mt-4 text-lg font-bold">{tx(d.zone)}</h3><p className="mt-1 text-sm text-muted-foreground">{tx(d.name)}</p><dl className="mt-5 space-y-2 text-sm"><div className="flex justify-between"><dt>{tx(uiText.landArea)}</dt><dd className="font-semibold">{d.land}</dd></div><div className="flex justify-between"><dt>{tx(uiText.power)}</dt><dd>{d.power}</dd></div><div className="flex justify-between"><dt>{tx(uiText.gas)}</dt><dd>{d.gas}</dd></div><div className="flex justify-between"><dt>{tx(uiText.water)}</dt><dd>{d.water}</dd></div></dl><Button asChild variant="outline" className="mt-6 w-full"><Link to="/map">{tx(uiText.viewMap)}</Link></Button></article>)}</div>;
 else if(page==="map") content=<div className="overflow-hidden rounded-3xl border border-border bg-card"><iframe title="Yandex map" src="https://yandex.com/map-widget/v1/?ll=67.2783%2C37.2242&z=11" className="h-[560px] w-full" loading="lazy"/><div className="border-t border-border p-5 text-sm text-muted-foreground">{tx(L("Харитада ер майдонлари ва инвестиция объектлари кўрсатилади.","На карте показаны земельные участки и инвестиционные объекты.","The map displays land plots and investment sites.","地图显示土地和投资项目。"))}</div></div>;
 else if(page==="export") content=<><div className="grid gap-5 md:grid-cols-3">{[["372.5m USD",L("2026 йил январь–июнь экспорти","Экспорт за январь–июнь 2026 года","Exports in Jan–Jun 2026","2026年1–6月出口")],["214.7m USD",L("Саноат маҳсулотлари экспорти","Экспорт промышленной продукции","Industrial exports","工业品出口")],["195",L("Экспортчи корхоналар","Предприятия-экспортёры","Exporting enterprises","出口企业")]].map(([v,x])=><article key={v as string} className="rounded-2xl border border-border bg-card p-6"><Globe2 className="size-6 text-green"/><p className="mt-4 text-3xl font-black text-primary">{v as string}</p><p className="text-sm text-muted-foreground">{tx(x)}</p></article>)}</div><div className="mt-8 space-y-3">{exportPartners.map(x=><div key={tx(x.country)} className="rounded-xl border border-border bg-card p-4"><div className="flex justify-between"><b>{tx(x.country)}</b><span className="font-bold text-primary">{x.share}%</span></div><p className="mt-1 text-sm text-muted-foreground">{tx(x.goods)}</p></div>)}</div></>;
 else if(page==="documents") content=<><SearchBox value={query} onChange={setQuery} placeholder={tx(uiText.searchDocument)}/><div className="mt-8 overflow-hidden rounded-2xl border border-border">{filteredDocs.map(d=><div key={tx(d.title)} className="flex flex-wrap items-center gap-4 border-b border-border bg-card p-5 last:border-0"><FileText className="size-6 text-primary"/><div className="min-w-0 flex-1"><h3 className="font-semibold">{tx(d.title)}</h3><p className="text-sm text-muted-foreground">{d.type} · {d.date}</p></div><Button asChild variant="outline"><a href={d.href} download={d.href!=="#"}><Download className="size-4"/> {tx(uiText.download)}</a></Button></div>)}</div></>;
 else if(page==="news") content=<div className="grid gap-5 md:grid-cols-3">{news.map(n=><article key={tx(n.title)} className="rounded-2xl border border-border bg-card p-6"><NewspaperIcon/><p className="mt-4 text-xs font-semibold text-green">{n.date}</p><h3 className="mt-2 text-lg font-bold">{tx(n.title)}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{tx(n.text)}</p></article>)}</div>;
 else if(page==="media") content=<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3,4,5,6].map(i=><article key={i} className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex aspect-video items-center justify-center gradient-brand"><ImageIcon className="size-12 text-white/75"/></div><div className="p-4"><h3 className="font-semibold">{tx(L(`Тадбирлар ва учрашувлар — ${i}`,`Мероприятия и встречи — ${i}`,`Events and meetings — ${i}`,`活动与会议 — ${i}`))}</h3><p className="mt-1 text-sm text-muted-foreground">{tx(L("Фото ва видео материаллар","Фото- и видеоматериалы","Photo and video materials","图片和视频资料"))}</p></div></article>)}</div>;
 else if(page==="contacts") content=<div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-6"><h2 className="text-xl font-bold">{tx(uiText.contactInfo)}</h2><div className="mt-6 space-y-5 text-sm"><p className="flex gap-3"><MapPin className="size-5 text-green"/>{t("contacts.address.value")}</p><a className="flex gap-3" href="tel:+998762241415"><Phone className="size-5 text-green"/>{CONTACTS.phones[0]}</a><p className="flex gap-3"><CalendarDays className="size-5 text-green"/>{t("contacts.hours.value")}</p></div><h3 className="mt-8 font-bold">{tx(uiText.officialPlatforms)}</h3><div className="mt-3 grid gap-3">{[["Invest.gov.uz","https://invest.gov.uz"],["Surxonstat.uz","https://surxonstat.uz"],["E-auksion.uz","https://e-auksion.uz"]].map(([a,b])=><a key={a} href={b} target="_blank" rel="noreferrer" className="flex items-center justify-between rounded-xl border border-border p-4 font-semibold hover:bg-muted">{a}<ExternalLink className="size-4"/></a>)}</div></div><iframe title="Yandex location" src="https://yandex.com/map-widget/v1/?ll=67.2783%2C37.2242&z=14" className="min-h-[500px] w-full rounded-2xl border border-border" loading="lazy"/></div>;
 else if(page==="reception") content=<div className="mx-auto max-w-2xl rounded-2xl border border-border bg-card p-6 sm:p-8">{sent?<div className="py-16 text-center"><CheckCircle2 className="mx-auto size-14 text-green"/><h2 className="mt-5 text-2xl font-bold">{tx(uiText.accepted)}</h2><p className="mt-2 text-muted-foreground">{tx(uiText.appealNo)}: SRX-{Date.now().toString().slice(-6)}</p></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}} className="grid gap-5"><div className="grid gap-5 sm:grid-cols-2"><Input required placeholder={tx(uiText.fullName)}/><Input required placeholder={tx(uiText.phone)}/></div><Input type="email" placeholder="Email"/><Input required placeholder={tx(uiText.subject)}/><Textarea required rows={7} placeholder={tx(uiText.message)}/><Button type="submit" size="lg"><Send className="size-4"/> {t("common.send")}</Button></form>}</div>;
 else if(page==="cabinet") content=<div className="mx-auto max-w-md rounded-2xl border border-border bg-card p-8"><ShieldCheck className="size-10 text-primary"/><h2 className="mt-5 text-2xl font-bold">{t("nav.cabinet")}</h2><p className="mt-2 text-sm text-muted-foreground">{tx(pageSubtitle.cabinet)}</p><form className="mt-7 grid gap-4"><Input type="email" placeholder="Email"/><Input type="password" placeholder={tx(uiText.password)}/><Button>{tx(uiText.signIn)}</Button><Button type="button" variant="outline">{tx(uiText.register)}</Button></form></div>;
 else { const items=(cardSets as any)[page]||cardSets.investments; content=<div className="grid gap-5 md:grid-cols-3">{items.map(([Icon,a,b]:any)=><article key={tx(a)} className="rounded-2xl border border-border bg-card p-6"><span className="flex size-12 items-center justify-center rounded-xl gradient-brand text-white"><Icon className="size-5"/></span><h3 className="mt-5 text-lg font-bold">{tx(a)}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{tx(b)}</p></article>)}</div> }
 return <SiteLayout><PageHero eyebrow={t("org.short")} title={title} description={tx(pageSubtitle[page]||pageSubtitle.investments)}/><section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">{content}</section></SiteLayout>;
}
function NewspaperIcon(){return <span className="flex size-11 items-center justify-center rounded-xl bg-blue-50 text-primary"><FileText className="size-5"/></span>}
