/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CabinetRouteImport } from './routes/cabinet'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndustryRouteImport } from './routes/industry'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as LandRouteImport } from './routes/land'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as MapRouteImport } from './routes/map'
import { Route as MediaRouteImport } from './routes/media'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StructureRouteImport } from './routes/structure'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabinetRoute = CabinetRouteImport.update({
  id: '/cabinet',
  path: '/cabinet',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryRoute = IndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureRoute = StructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/industry': typeof IndustryRoute
  '/investments': typeof InvestmentsRoute
  '/land': typeof LandRoute
  '/leadership': typeof LeadershipRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/reception': typeof ReceptionRoute
  '/services': typeof ServicesRoute
  '/staff': typeof StaffRoute
  '/structure': typeof StructureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/industry': typeof IndustryRoute
  '/investments': typeof InvestmentsRoute
  '/land': typeof LandRoute
  '/leadership': typeof LeadershipRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/reception': typeof ReceptionRoute
  '/services': typeof ServicesRoute
  '/staff': typeof StaffRoute
  '/structure': typeof StructureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabinet': typeof CabinetRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/export': typeof ExportRoute
  '/industry': typeof IndustryRoute
  '/investments': typeof InvestmentsRoute
  '/land': typeof LandRoute
  '/leadership': typeof LeadershipRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRoute
  '/reception': typeof ReceptionRoute
  '/services': typeof ServicesRoute
  '/staff': typeof StaffRoute
  '/structure': typeof StructureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cabinet'
    | '/contacts'
    | '/documents'
    | '/export'
    | '/industry'
    | '/investments'
    | '/land'
    | '/leadership'
    | '/map'
    | '/media'
    | '/news'
    | '/projects'
    | '/reception'
    | '/services'
    | '/staff'
    | '/structure'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cabinet'
    | '/contacts'
    | '/documents'
    | '/export'
    | '/industry'
    | '/investments'
    | '/land'
    | '/leadership'
    | '/map'
    | '/media'
    | '/news'
    | '/projects'
    | '/reception'
    | '/services'
    | '/staff'
    | '/structure'
  id:
    | '__root__'
    | '/'
    | '/cabinet'
    | '/contacts'
    | '/documents'
    | '/export'
    | '/industry'
    | '/investments'
    | '/land'
    | '/leadership'
    | '/map'
    | '/media'
    | '/news'
    | '/projects'
    | '/reception'
    | '/services'
    | '/staff'
    | '/structure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabinetRoute: typeof CabinetRoute
  ContactsRoute: typeof ContactsRoute
  DocumentsRoute: typeof DocumentsRoute
  ExportRoute: typeof ExportRoute
  IndustryRoute: typeof IndustryRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LandRoute: typeof LandRoute
  LeadershipRoute: typeof LeadershipRoute
  MapRoute: typeof MapRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRoute
  ProjectsRoute: typeof ProjectsRoute
  ReceptionRoute: typeof ReceptionRoute
  ServicesRoute: typeof ServicesRoute
  StaffRoute: typeof StaffRoute
  StructureRoute: typeof StructureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabinet': {
      id: '/cabinet'
      path: '/cabinet'
      fullPath: '/cabinet'
      preLoaderRoute: typeof CabinetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry': {
      id: '/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof IndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure': {
      id: '/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabinetRoute: CabinetRoute,
  ContactsRoute: ContactsRoute,
  DocumentsRoute: DocumentsRoute,
  ExportRoute: ExportRoute,
  IndustryRoute: IndustryRoute,
  InvestmentsRoute: InvestmentsRoute,
  LandRoute: LandRoute,
  LeadershipRoute: LeadershipRoute,
  MapRoute: MapRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRoute,
  ProjectsRoute: ProjectsRoute,
  ReceptionRoute: ReceptionRoute,
  ServicesRoute: ServicesRoute,
  StaffRoute: StaffRoute,
  StructureRoute: StructureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
